#!/bin/bash
# 
#--------------------------------------------------------------------
#
# script to run automake tools
#
# Mike Dixon, EOL, NCAR, Boulder, CO, USA
# Sept 2017
#
#--------------------------------------------------------------------

# set the path

export PATH=.:/bin:/usr/bin:/sbin:/usr/sbin:/usr/bin/X11:/usr/local/bin:/usr/local/sbin

#--------------------------------------------------------------------
# usage function
#

function usage() {
    echo
    echo "Usage: run_autoconf [ -verbose -h ]"
    echo
    echo "  -h:     produce this usage list"
    echo "  -verbose: turn debugging on"
    echo
}

#--------------------------------------------------------------------
# check args

if [ $# -gt 2 ]
then
    echo "ERROR - bad command line"
    usage
    exit -1
fi

if [ "$1" == -h -o "$2" == -h ] 
then
    usage
    exit 0
fi

verbose=false
if [ "$1" == -verbose -o "$2" == -verbose ] 
then
    verbose=true
fi

# Run the scripts for autoconf

if [ "$verbose" == true ] 
then
  aclocal --verbose
  autoheader --verbose
  automake --add-missing --verbose
  autoconf --verbose
else
  echo "running aclocal ...."
  aclocal
  echo "running autoheader ...."
  autoheader
  echo "running automake ...."
  automake --add-missing
  echo "running autoconf ...."
  autoconf
fi

